# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09d08ca3e9f7739285b721587cdea75c7a56be0d1e65819517bfa0c8cb10bf0353a2820575166a2bd1626517a7f880e31d0e68c234844f91eb97632af91029a6

test:
  secret_key_base: 194f9ac6328e5d2bf6d060ef3ff7a5b5a621fbf42d57263212af123aee543fb1a0358dc6d3ce08f6823fa73e8ea742bec826ba641e1a6586f9acb28b24d8c352

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
